### ISSUE TITLE
voice search

### ISSUE THREAD

**Issue by TiuDerca** [webosbrew/youtube-webos#1]
voice search does not work
opening links does not work during voice search in the system, it just opens the application

webos 5+

the best application for bypassing ads, unfortunately for all 5+ webos users it is of little use without these functions

**Comment by Informatic** [comment]
Sadly I don't have webOS 5.x device to test this out on.

Can you please try launching a video from voice search, open developer toolbar on http://TV_IP:9998, then switch to "Console" tab, enter `window.launchParams` in bottom text input box and show me what you get?
Optionally, there may be `RELAUNCH: ...` message in the logs, that would be useful as well.

**Comment by fire332** [comment]
Similar issue on webOS 6.  Trying to launch videos directly from the webOS home screen only goes to the homepage.

![image](https://user-images.githubusercontent.com/96039230/145762867-848eec1a-0057-4187-8e00-0f5179bd1ede.png)
