### ISSUE TITLE
Feature request: block shorts in interface 

### ISSUE THREAD

**Issue by Rajackar** [webosbrew/youtube-webos#105]
Do you think it will be possible to add a feature to hide YouTube shorts?
I see other ad blocking apps are adding this and would love to see it.

**Comment by andrasmaroy** [comment]
I'd love to see this as well!

**Comment by zakrzk** [comment]
I'd love to see this feature too :)

**Comment by JaCzekanski** [comment]
I prototyped this today, see #201
