### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by heltsonika** [webosbrew/youtube-webos#109]
It seems Youtube blocked the audio. Anyone else with this issue?

**Comment by jospezial** [comment]
Caused by first tile (ad). Fix was merged with #100 
@throwaway96 @Informatic could you please tag a new (pre)release? That should close some issues.
Last release is now almost 2 years old and some important improvements were merged in that time.

**Comment by heltsonika** [comment]
It turned out to be a faulty home receiver. Case closed
