### ISSUE TITLE
Does not save videos to YouTube

### ISSUE THREAD

**Issue by strdik** [webosbrew/youtube-webos#11]
Hello, please solve the problem in YouTube, does not save the place where the video stops after re-enabling the video starts first on version 0.2.1. Check everything properly and update the new version. If you fix everything, thank you very much in advance!!!

**Comment by Informatic** [comment]
https://github.com/webosbrew/youtube-webos/issues/13#issuecomment-1004038858
Please check if that version doesn't accidentally fix that issue for you.
Also please make sure you are really logged into Your Google account. This version works perfectly fine for me.

**Comment by adamanolog** [comment]
Здравствуйте,не работает воспроизведение с последнего места остановки, видео начинается сначала,помогите решить проблему
