### ISSUE TITLE
Thumbnail are in low resolution

### ISSUE THREAD

**Issue by kurisutofu** [webosbrew/youtube-webos#111]
Hi,
The thumbnails are showing in low resolution.
Is there a way to fix that or will it need some fix?

**Comment by cremor** [comment]
I also immediately noticed this when switching from the official YouTube app. It is especially ugly in the menu screens (like the home screen), but the preview thumbnail that is shown when scrolling over the video timeline is also affected.

**Comment by cremor** [comment]
Looks like this is fixed in v0.3.2-rc1. At least I don't see any obviously low quality thumbnails right now.

**Comment by kurisutofu** [comment]
> Looks like this is fixed in v0.3.2-rc1. At least I don't see any obviously low quality thumbnails right now.

Nice. The homebrew app does not  update to 0.3.2 but I'll try as soon as it's available.

**Comment by throwaway96** [comment]
This should be fixed in 0.3.2.

**Comment by Gartorf** [comment]
I just installed what I believe to be the latest version (0.3.4) yesterday, and all thumbnails are low resolution.
Any known fix?
