### ISSUE TITLE
no transparency

### ISSUE THREAD

**Issue by PINKeHamton** [webosbrew/youtube-webos#113]
when i watch a video it dose not and hit up it has a solid black back ground

**Comment by cremor** [comment]
Yes, please add transparency support for the player interface elements!
For the buttons it would be nice to have (better visual style). But it is essential for the recommended videos section because that blocks halve of the screen otherwise.

**Comment by ArcanjoMan** [comment]
how do I do that? I can't do it, could you please make a tutorial that would help me a lot to do it here on television.

**Comment by throwaway96** [comment]
I'm going to assume this is referring to the same problem as #118. If not, let me know, and I'll reopen.
