### ISSUE TITLE
Integration with youtube-webos-cobalt-browser? 

### ISSUE THREAD

**Issue by illuvattarr** [webosbrew/youtube-webos#119]
GuillaumeSmaha has made an extension of this app to work with Cobalt, which is also the default browser that the official youtube app uses. It enables use of HTML5 and would support video speed modification. However, it currently has to be compiled manually. 

https://github.com/GuillaumeSmaha/youtube-webos-cobalt-browser

Would it be possible to integrate this fork within the app so it can be easily installed through homebrew?

Would be much appreciated for lots of people I guess.

**Comment by throwaway96** [comment]
As it would involve copyrighted material not owned by or licensed to us, no. We don't need that kind of legal exposure.
