### ISSUE TITLE
TV enters Screensaver only on specific channel

### ISSUE THREAD

**Issue by schnills** [webosbrew/youtube-webos#12]
Hi, 

a rather strange/funny issue: I'm on 0.20 and it's working like a charm. But funnily on videos by Linus Tech Tips, only on videos by this channel but seemingly on all videos by this channel, after a two minutes or something my TV enters screensaver mode although the video is running :D 
Never happened when watching videos by other channels I frequently visit. 

I'm really interested in what makes this happen from technical perspective, so if you could have a look at it and let me know that'd be great :D Maybe I'll have a look at debug view, but as I'm not into the code at all, dunno if I could read anything out of it. 

Thanks!

**Comment by Informatic** [comment]
Does that happen right when jumping between sponsor segments?

**Comment by triumfas** [comment]
I'm on the latest version and it also in some videos goes to Screensaver mode. It's definitely not related with sponsor at least in my case. Watching concert and it just goes to click in the middle of the song.

**Comment by schnills** [comment]
Yeah it happens just in during normal video content, not corresponding to sponsor segments etc. 
Dunno the timeout settings, but on videos by specific channels it just goes to screensaver mode after 2-3 minutes like normally when doing nothing. 
Like I said, I'm super curious what makes this happen only with specific channels. 
@triumfas what channel/video were you watching when this happened?

**Comment by triumfas** [comment]
https://youtu.be/stEXCmI_KK4 . Also happened with some Queen videos, just can't recall. I'll share if I find others.
