### ISSUE TITLE
Voice Search Not Working

### ISSUE THREAD

**Issue by deten** [webosbrew/youtube-webos#121]
The ability to search using voice input is not working.  Hasn't been for some time.  Would love to get an update to this!

**Comment by dmcodex** [comment]
hello try using the mic button on your magic remote rather than the app it ex " heres what i found on youtube for XX"
little work around until there is a fix

**Comment by throwaway96** [comment]
Have you tried this with [v0.3.2-rc1](https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.2-rc1)?

**Comment by deten** [comment]
Currently using 0.3.4 and still doesnt work.

On my LG C1 when I hit the "yellow" button which is what opens search/voice search.  It does not ever activate voice search and there is no button to use voice search manually on screen.

**Comment by l0ud** [comment]
I have the same issue. Oled B1

**Comment by fire332** [comment]
Fixed with #240.
