### ISSUE TITLE
Surround sound / dolby atmos support

### ISSUE THREAD

**Issue by Seb-** [webosbrew/youtube-webos#124]
Hello,

Thank you for the app!

Is there any chance to support surround sound / dolby atmos?

It's available from the official app on the videos that have the option, but unless I'm mistaken this app currently doesn't support it?

**Comment by throwaway96** [comment]
As far as I know, that is not realistic.

**Comment by JMY1000** [comment]
Out of curiosity, can I ask why that's not realistic?
