### ISSUE TITLE
Voice search

### ISSUE THREAD

**Issue by stm38** [webosbrew/youtube-webos#13]
A very good app, but there is an annoying problem. 
Voice search via LG Magic Remote does not work. After the voice request, the youtube popup appears, but there is no search result. Normal search works.

TV 55SM8600PLA
WebOS 4.9.3-5380409
Firmware 05.10.30

**Comment by Informatic** [comment]
Hey. Yeah, thanks. We are still debugging this. Seems like this is very platform dependent, we have someone testing it out on multiple version. I'll try to package up a modified version for you to test out is it works in your case in ~12h.

**Comment by Informatic** [comment]
```sh
luna-send -n 1 'luna://org.webosbrew.hbchannel.service/install' '{"ipkUrl":"http://d.inf.re/b/d90dedfe33749aac25d6f657526d277b.ipk", "ipkHash":"a197b76301823f784de552bf2d9fb5616348bb919a3934304d492b3b7a978ffa"}'
```
This shall install an updated version of youtube-webos. A reboot may be required.

**Comment by strdik** [comment]
And where you updated it is worth 0.2.1 the video both did not save and does not save if I stop in the middle after re-enabling it starts from the beginning and the account is configured correctly one on all devices and saves everywhere, please solve this problem with a new update.
