### ISSUE TITLE
Autostart disable wrong command

### ISSUE THREAD

**Issue by ANewDawn** [webosbrew/youtube-webos#130]
Noticed in wiki autostart disable is missing the -pub in the command. Should be

luna-send-pub -n 1 'luna://com.webos.service.eim/deleteDevice' '{"appId":"youtube.leanback.v4"}'

**Comment by throwaway96** [comment]
`/deleteDevice` is indeed public (at least on webOS 6). Submit a PR, and I'll merge it.

**Comment by ANewDawn** [comment]
Sorry I'm not familiar with creating PRs

**Comment by throwaway96** [comment]
For something like this, you can just click the edit icon on `README.md`, make the change, click commit, and basically just follow what it says on the screen. GitHub makes it pretty easy.

<https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request>

**Comment by ANewDawn** [comment]
Created a PR there.

Cheers

**Comment by throwaway96** [comment]
Fixed by #131.

Note that `luna-send` works too, as long as you have root.
