### ISSUE TITLE
Adblock

### ISSUE THREAD

**Issue by heroic20** [webosbrew/youtube-webos#136]
Adblock no longer works.

**Comment by throwaway96** [comment]
Can you provide some more information?

What specifically are you talking about? Do you have a screenshot or an example video where ads are not blocked? What webOS version are you running? Which version of the app are you using? And so on...

**Comment by heroic20** [comment]
When clicking on a video, an un-skippable ad appears with a timer. WebOS Software version: 04.40.94.  The Youtube app version is: web_20240325_10_RC00. I uninstalled the application and reinstalled the app in the home-brew channel app. Latest should be version 0.3.2. 
![IMG_4529](https://github.com/webosbrew/youtube-webos/assets/44916050/8bec7fce-0530-4627-aeee-251196d74f76)

**Comment by throwaway96** [comment]
Try this build: <https://github.com/throwaway96/youtube-webos/releases/tag/v0.3.3-dev3>

**Comment by throwaway96** [comment]
Probably fixed by #142.

**Comment by fily1212** [comment]
Am I able to install it in a not rooted lg tv? I am in version 0.3.2 and I see all the ads. In webosbrew I can't see the update button enabled.

**Comment by throwaway96** [comment]
> Am I able to install it in a not rooted lg tv?

Yes. You can use:

* [Dev Manager](https://github.com/webosbrew/dev-manager-desktop)
* The command line via SSH (information: [connecting via SSH](https://gist.github.com/throwaway96/e811b0f7cc2a705a5a476a8dfa45e09f#alternative-clients); [installing apps](https://gist.github.com/throwaway96/e811b0f7cc2a705a5a476a8dfa45e09f#cmdline-install))
* `ares-install` from the [webOS CLI tools](https://github.com/webos-tools/cli)
* Homebrew Channel, if you add [my repo](https://throwaway96.github.io/apps-repo/api/apps.json): `https://throwaway96.github.io/apps-repo/api/apps.json` (but be careful about installing anything else from there)
