### ISSUE TITLE
Bug: Syntax error on webOS 3.0

### ISSUE THREAD

**Issue by throwaway96** [webosbrew/youtube-webos#151]
See webosbrew/webos-homebrew-channel#179 ([here](https://github.com/webosbrew/webos-homebrew-channel/issues/179#issuecomment-2031687673)).

**Comment by jospezial** [comment]
The non working green button and no adblock in videos is since https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.3-rc1
That works in https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.2

**Comment by throwaway96** [comment]
Please try this build: <https://github.com/throwaway96/youtube-webos/releases/tag/v0.3.4-dev1>

**Comment by fire332** [comment]
@throwaway96 To reply to your comment [here](https://github.com/webosbrew/youtube-webos/pull/146#issuecomment-2036031243), the updates to some babel dependencies could be related but that's all I got. Have you looked at the diff to see where it's erroring?

**Comment by jospezial** [comment]
> Please try this build: https://github.com/throwaway96/youtube-webos/releases/tag/v0.3.4-dev1

adblock works again when playing videos.
Can navigate in adblock menu but checkboxes don't change with "OK" -key.

When I was on first ad tile in "recommended" and pressed green key, the adblock menu window did not have the focus?
Up/down moved through video tiles behind the adblock menu.

**Comment by fire332** [comment]
> When I was on first ad tile in "recommended" and pressed green key, the adblock menu window did not have the focus?
Up/down moved through video tiles behind the adblock menu.

I've noticed this too on my C1 on my branch. I have to wait a little bit after opening the config menu before pressing up/down to navigate through the config menu or the focus will still be in youtube for some reason.

**Comment by cremor** [comment]
> Can navigate in adblock menu but checkboxes don't change with "OK" -key.

Maybe related to #143?



> When I was on first ad tile in "recommended" and pressed green key, the adblock menu window did not have the focus?
> Up/down moved through video tiles behind the adblock menu.

This is not a new problem, I've already seen this in older verisons. Just close and open the settings again and it should work.

**Comment by igorkulman** [comment]
> Please try this build: https://github.com/throwaway96/youtube-webos/releases/tag/v0.3.4-dev1

I can confirm this also works for me.

**Comment by throwaway96** [comment]
@cremor

> This is not a new problem, I've already seen this in older verisons. Just close and open the settings again and it should work.

Did you have this problem in 0.3.1 or older?

**Comment by cremor** [comment]
> Did you have this problem in 0.3.1 or older?

0.3.1 was the current version when I started to use the app, and it was the version where I noticed it first.

**Comment by Meth69** [comment]
> Please try this build: https://github.com/throwaway96/youtube-webos/releases/tag/v0.3.4-dev1

I'm on webOS 3.9.0 and can confirm the 0.3.4-dev1 works, whereas 0.3.3 didn't open the settings menu and didn't block ads.

**Comment by throwaway96** [comment]
Should be fixed as a side effect of #146.

Please try [0.3.4-rc1](https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.4-rc1).

**Comment by jospezial** [comment]
> [0.3.4-rc1](https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.4-rc1)

Can navigate in adblock menu but checkboxes don't change with "OK" -key.
The adblock menu window still looses focus and then remote control controls youtube in background.

**Comment by throwaway96** [comment]
@jospezial 

See #157.

**Comment by throwaway96** [comment]
Well, this has been fixed at least. Ugh.
