### ISSUE TITLE
If you don't mind, could you build an original YouTube icon version?

### ISSUE THREAD

**Issue by bjw5612g** [webosbrew/youtube-webos#152]
I found this application is very useful for my LG OLED TV and enjoying it with great thanks. 

However, the application has different icon from original YouTube application. So, my young kids ask me where is YouTube application everytime. 

So if you don't mind, I think it will be easy for people to use without getting confused if you provide Original YouTube icon version.

Again, thanks for your great job.

**Comment by throwaway96** [comment]
Sorry, but we can't do that for intellectual property reasons.

If you would like to build something like that yourself, you could install the stock YouTube app and grab the icons from `/media/cryptofs/apps/usr/palm/applications/youtube.leanback.v4`. They're probably named something like `yt_lg_80x80.png` and `yt_lg_130x130.png`. You would replace `assets/icon.png` with `yt_lg_80x80.png` and `assets/largeIcon.png` with `yt_lg_130x130.png`.

Alternatively, if you don't have a rooted TV, there are stock YouTube IPKs available at [`webosouxon/youtube-webos-cobalt-ipks`](https://github.com/webosouxon/youtube-webos-cobalt-ipks) along with a script to extract them.

You should be able to build your own ad-free IPK by forking this repo, enabling actions, and creating a release.
