### ISSUE TITLE
Ads show up at the beginning of the video 

### ISSUE THREAD

**Issue by maciek226** [webosbrew/youtube-webos#155]
Since yesterday I started seeing ads at the begging of videos using the app. I updated yesterday to the most recent version.

**Comment by JRStrikwerda** [comment]
Same issue here. Ads at the start and end of videos are back. I have the latest version of youtube-webos v0.3.2

**Comment by maciek226** [comment]
I actuary found another issue that mentions this. Looks like the update was pulled due to issues on older os versions.
https://github.com/webosbrew/youtube-webos/issues/154

**Comment by JRStrikwerda** [comment]
@maciek226 Thanks. Manually updating to 0.3.3 fixed the issue.

**Comment by andreikrutsko** [comment]
@JRStrikwerda is 0.3.3 released?  it is not list yet

**Comment by JRStrikwerda** [comment]
@andreikrutsko its not, I updated manually.

**Comment by BLKKKBVSIK** [comment]
I can confirm, 0.3.3 resolve the issue.
You have to build the ipk manually.

**Comment by besendorf** [comment]
@throwaway96 could you build a new version and publish it on the homebrewchannel?
Thanks in advance

**Comment by PeteOvgard** [comment]
Go to https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.3-rc2
and download the IPK, and in Dev Manager, click in install, and open the IPK file.

**Comment by Meth69** [comment]
Version 0.3.3 doesn't work for me on WebOS 6.00.25, doesn't even open the adblock settings menu when pressing the green button, just looks like using the default Youtube app even though it's not (and I've uninstalled it). Not sure if I'm the only one with this problem.

**Comment by throwaway96** [comment]
@Meth69

06.00.25 is not a webOS version. See #151.

**Comment by Meth69** [comment]
> @Meth69
> 
> 06.00.25 is not a webOS version. See #151.

Sorry, you're right, I'm on 3.9.0 and everything seems to be working again with 0.3.4-dev1, thanks.

**Comment by bedenko** [comment]
I've tried v0.3.3-rc2, but ads are still present.

**Comment by throwaway96** [comment]
Please try [0.3.4-rc1](https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.4-rc1).

**Comment by besendorf** [comment]
> Please try [0.3.4-rc1](https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.4-rc1).
> 
> Closing as duplicate of #154. (See also #136, #151.)

works for me
