### ISSUE TITLE
Is there a similar project for LG Netcast TVs?

### ISSUE THREAD

**Issue by rmadeira147** [webosbrew/youtube-webos#165]
I still have an LG TV that runs Netcast and I would like to know if there is any project that makes it possible to install apps on it.

**Comment by jospezial** [comment]
Maybe this works?
https://github.com/throwaway96/youtube-webos/releases/tag/v0.3.2-webkit1
The question is how you get access into the TV. Developer mode or https://github.com/webosbrew/webos-homebrew-channel ?

**Comment by rmadeira147** [comment]
Thanks for the answer.  But it would only be possible if there was a well explained and safe way, just like for webos.

**Comment by throwaway96** [comment]
I'm not aware of any current development targeting NetCast.
