### ISSUE TITLE
Bug: <YTAF doesnt work anymore>

### ISSUE THREAD

**Issue by george-idgaf** [webosbrew/youtube-webos#166]
## YTAF information

- YTAF version: 0.3.3

## TV information

- webOS version: 3.9.0
- Firmware version: 06.10.35
- OTAID: HE_DTV_W17R_AFAAABAA
- SoC: m2r

## Issue description

i have been using this mod for quite a while and have never experienced issues until recently. firstly, i updated my tv (i think)
afterwards, the ytaf app wouldn't open up anymore. i unplugged my tv and replugged it and the homebrew and the ytaf were gone. i figured out i needed to update the homebrew and reinsatll it. the developer wasn't connected anymore either. now, after struggling for quite some time to install both apps, it seems that the YTaf doesnt work as it's supposed to. no adblocking and the green button doesn't work. is there anything to do ?

**Comment by jospezial** [comment]
https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.4-rc1 should fix this.
Easy install with https://github.com/webosbrew/dev-manager-desktop/tags

**Comment by george-idgaf** [comment]
Thank you, jospezial! It now works just how it's supposed to!
