### ISSUE TITLE
Youtube does not save the video stop location

### ISSUE THREAD

**Issue by dryna2017** [webosbrew/youtube-webos#17]
Hello, will you ever solve the problem with YouTube it is impossible to watch like this, you have to rewind to the place where you finished watching, the video does not save the place where you finished watching, everything is correctly configured and connected. Update be so kind and fix the bugs.

**Comment by Informatic** [comment]
Sorry for being harsh, but do you seriously think I didn't see ~15 of (presumably yours) comments/tickets I got so far about this?

I was unable to reproduce this after applying fixes mentioned in v0.2.0 changelog, nor have anyone offered to test and debug it themselves. Unless you want to send a shipment of various webOS hardware in my general direction and pay for my extra work on this, there's really not much I can do now.

If that is such a major issue, you may probably want to stick with the official YouTube app.

**Comment by strdik** [comment]
Yes, the same trouble, I already wrote, but there's no sense watching the video finished for 30 minutes, I had to leave, I came on and everything starts again, even though you write down where you finished, on standard YouTube, everything remembers what it takes so long to watch and fix that it would remember the place of the stop.

**Comment by Informatic** [comment]
BTW. I wouldn't be *too* surprised if this turned out to be some succeeded/failed YouTube AB Test applied only to Russian-speaking users, hence the reason I was unable to reproduce this... Sorry, not migrating yet.

**Comment by dryna2017** [comment]
Well, you can hope and wait for a correction that will save the history

**Comment by dryna2017** [comment]
А что значит неудачным тестом YouTube AB и еще не мигрировал, это что обозначает

**Comment by Informatic** [comment]
What would be potentially useful is:
1. Tell us all the information you get in "YouTube App → Settings → App Version"
2. Result of running this command using Telnet or SSH: `grep -h -E '"(hardware_id|core_os_release|product_id|webos_manufacturing_version|board_type)"' /var/run/nyx/*`
3. Photos or a video that describes your issue. Maybe I am just missing something.

**Comment by dryna2017** [comment]
![IMG_20220107_164638](https://user-images.githubusercontent.com/96721916/148553026-d46d5bec-3d4d-4f67-9906-cafd95abe533.jpg)

**Comment by dryna2017** [comment]
And that this command should be entered and what it will give
![Screenshot_21](https://user-images.githubusercontent.com/96721916/148553655-5366536b-da71-4f73-bbd6-ba9a70b4ccd3.png)

**Comment by dryna2017** [comment]
I entered this command, and then what

**Comment by Informatic** [comment]
That is useful, thank you.

**Comment by dryna2017** [comment]
The problem is when you watch a movie and stopped in the middle, paused and left YouTube, after when you went to the video that you watched starts first, and not from the place where you stopped for a pause, and on the phone if you stop the video in the middle, then on the TV it will show from the place where you stopped on the phone. If you understand how I explained, help in any way you can. Thanks!!!

**Comment by dryna2017** [comment]
А что вы имели в виду это полезно.

**Comment by dryna2017** [comment]
And what did you mean it's useful

**Comment by zizzyhax** [comment]
It means that the information was useful.

**Comment by dryna2017** [comment]
So can you help with something

**Comment by dryna2017** [comment]
Так сможете чем помочь

**Comment by zizzyhax** [comment]
Maybe

**Comment by dryna2017** [comment]
Hello, you have not answered, we will be helped from YouTube, I have sent the data.

**Comment by dryna2017** [comment]
> Это полезно, спасибо.

I sent you the data you can solve the problem with YouTube so that the browsing history is saved

**Comment by zizzyhax** [comment]
@dryna2017 STOP SPAMMING.

Every time you create a new issue, you problem is less likely to be fixed. Stop spamming and wait patiently, or you will be reported to GitHub for spamming and you will be banned.

**Comment by 1basti1** [comment]
I also have this problem. But not on all videos. Only some. Maybe the majority, but many videos don't have this problem. And I'm not from Russia. I'm in Germany with German language in the app. It's quite annoying. But still better than ads.

**Comment by Informatic** [comment]
If you have telnet/ssh working or know how to manually install `ipk` - please test: https://github.com/webosbrew/youtube-webos/pull/24#issuecomment-1013831027
