### ISSUE TITLE
Ads are now appearing. Google has found a workaround

### ISSUE THREAD

**Issue by kurupted** [webosbrew/youtube-webos#171]
It's been great for a year but there's no ads before videos, with a new ad UI. Any chance of a fix?

**Comment by mrwedders** [comment]
Are you using the latest version?

I saw some ads this morning too but I was running 0.3.1. Just updated to 0.3.4 and everything seems fine again!

**Comment by mhamzas** [comment]
Facing the same issue - updated the latest version, still seeing the ads.

**Comment by WhiskeyBest** [comment]
Been facing the same issue on and off for a month. Started only seeing ads on one account, but now I see ads on all youtube accounts, consistently for a few days now.

**Comment by mhamzas** [comment]
Any workaround?

**Comment by kurupted** [comment]
Turns out I wasn't using the latest version afterall :x
Or if I wasn't then, I am now (just updated) and the ads seems to be gone :)

**Comment by mhamzas** [comment]
What's the version you're using now? Link?

Regards,
M Hamza Siddiqui
http://www.linkedin.com/in/mhamzas

**Comment by kfoofw** [comment]
I'm on 0.3.4 and my LG TV has ads at the start of the Youtube videos (but not in the midst of the videos) and I think they are Sponsored Ads.

**Comment by Paul-Etienne** [comment]
I've had this problem for months now, with the ads using the new UI. And upgrading the version of YouTube Ad Free only ever makes things worse. I'm currently running v0.3.1 as it's the only one I've tested that only has ads before a video and not during. I've tested v0.3.3 and v0.3.4 and they both give me ads before videos and also during.

**Comment by cremor** [comment]
If you have an old TV with webOS version 1 or 2 then the current version of this app will not work for you.
See #160 (which also has a link to a special fixed version for webOS 1 and 2).

**Comment by Paul-Etienne** [comment]
My TV is 6/7 yo, but the "About my TV" section lists a software version 04.06.75 or something like that. That means it's running webOS 4 right?

**Comment by cremor** [comment]
No. Firmware/Software version is different from WebOS version.

**Comment by Paul-Etienne** [comment]
Oh okay, then it's probably an older webOS version. Can one check that in the TV menus somewhere? Or do we have to look on the Internet with the TV model?

**Comment by Paul-Etienne** [comment]
I forgot to mention, you were right 👍 Using the webOS 1/2 version did the trick, I no longer have ads, thank you very much!

**Comment by fire332** [comment]
Root cause of this issue is either using an outdated version or requiring a legacy build for webOS 1/2.
