### ISSUE TITLE
Video thumbnails gone pixelated/load in low resolution again

### ISSUE THREAD

**Issue by JRD2000x** [webosbrew/youtube-webos#175]
Minor issue but annoying...hopefully the dev will push another build whenever possible

**Comment by rmadeira147** [comment]
Here I was using version 0.3.3 and I thought it was a bug.  I updated to 0.3.4 and it continues.  This is on an OLED 55C1PSA. Still, congratulations to the developers of this spectacular project.

**Comment by useman** [comment]
Same problem

**Comment by fire332** [comment]
Closing in favor of #196.
