### ISSUE TITLE
Speed change option not available

### ISSUE THREAD

**Issue by ayushs-2k4** [webosbrew/youtube-webos#184]
## YTAF information

- YTAF version: 0.3.4

## TV information

- webOS version: 
- Firmware version: 03.40.82
- OTAID:
- SoC:
- Model:

## Issue description

Speed change option not available in YTAF, but it is available in official Youtube. Please look into this issue urgently.

**Comment by throwaway96** [comment]
Please see #6, #39, #52, #65, #76, #178 (urgently).
