### ISSUE TITLE
youtube search shows very old videos - how to sort by latest date

### ISSUE THREAD

**Issue by vkkindia** [webosbrew/youtube-webos#185]
Whenever i search video "pop songs latest" from the app, i am getting list of videos dated 2 years, 6 years, very old ones too.
Anyway to specify sort by date. In android app or website it is showing very relevant results.

**Comment by kitsuned** [comment]
ask the Google engineers ;)

YTAF does not influence recommendations in any way. YTAF is also not a third-party client, so its behavior should conform to the official app, well, except for blocking ads.
