### ISSUE TITLE
Feature Request: Add button to skip SponsorBlock Segments

### ISSUE THREAD

**Issue by RG007JM** [webosbrew/youtube-webos#186]
The title is pretty explanatory, would it be possible to have the option to skip the segment by clicking one of the coloured buttons? (Like the one we use to open the menu)
I understand this isn't wouldn't be an important feature, but it would benefit the users who use this feature in the other apps that have integrated the SponsorBlock API.

**Comment by cremor** [comment]
See #101, which also discussed skipping segments with key presses when automatic skipping is disabled.
