### ISSUE TITLE
Video titles appearing as squares

### ISSUE THREAD

**Issue by artemisxrpg** [webosbrew/youtube-webos#188]
- YTAF version: 0.3.4

## TV information

- webOS version: 04.50.56
- Firmware version: 5.5.0
- OTAID: HE_DTV_W20P_AFADATAA
- SoC: k6lp
- Model: 55UN7300AUD

![NBX_Snapshot_2024-05-03_04-20-02-899](https://github.com/webosbrew/youtube-webos/assets/74358884/1786b6ec-1676-4c9e-8c75-19281883d762)

Seems to only be happening to the adfree version, normal youtube didn't have this issue when I still had it installed. Only seems to be affecting some videos.

**Comment by itsRealM12C** [comment]
Probably because of font. The app is does not supports different font and this is why it shows the titles as squares.

**Comment by itsRealM12C** [comment]
I mean the app does supports the font but the creator used a website for different font and does not supports it.

**Comment by itsRealM12C** [comment]
I think Lmao Clip is speaking squares xD Videos title is literally "[][][] [][][][][][] [][][] [][] [][][][][] [][][].".

**Comment by cremor** [comment]
It's not a different font. The squares are shown for non-standard unicode characters. It also happens with smileys.

The example from the screenshot provided in the first comment looks like this on a PC:
![grafik](https://github.com/user-attachments/assets/e6806ef4-2072-4499-b035-eb631cfa09d7)
Link to the video: https://www.youtube.com/watch?v=JX6HW7DFYwE

When you copy and paste some of those bold looking characters to https://www.compart.com/en/unicode/ you'll see that those are actually different unicode characters.
The first character of the example video title is https://www.compart.com/en/unicode/U+1D5D5
A normal "B" is https://www.compart.com/en/unicode/U+0042

**Comment by itsRealM12C** [comment]
i mean the text are bold and unicode and thats why bruh. Im out.

**Comment by itsRealM12C** [comment]
On PC it supports the unicode but on TV not except if you using official version of YouTube.

**Comment by throwaway96** [comment]
I assume this was tested on the new cobalt-based official app. Can someone try this on the WAM version?
