### ISSUE TITLE
Feature Request: Comments and more

### ISSUE THREAD

**Issue by itsRealM12C** [webosbrew/youtube-webos#190]
So. We need the feature for adfree app that you can comment exactly like on PC and on phone, but on TV too! Also, we need a special button, which is seeing the privated videos, unlisted videos, deleted videos, and members only video, yt premium only video and deleted channel. Please make that update as soon as possible. Is that a bad idea anyways? (my opinion is it's impossible to watch privated videos and etc.).

**Comment by throwaway96** [comment]
Out of scope for this project.

**Comment by itsRealM12C** [comment]
Add that feature immediately or else i will replace adfree to official version xD
(not forcing)

**Comment by throwaway96** [comment]
Please stop wasting our time with pointless issues. You are already close to being banned because of your behavior on Discord.

**Comment by itsRealM12C** [comment]
im not behaving sir. im being nice.

**Comment by itsRealM12C** [comment]
misbehaving*
