### ISSUE TITLE
Low quality thumbnails 

### ISSUE THREAD

**Issue by Deadinsidee3** [webosbrew/youtube-webos#196]
I installed the application using dev manager on PC, everything went well, the only problem I have is that the YouTube thumbnails on the TV look very low quality, is there any way to fix this? 

I tried reinstalling and it's still the same.

**Comment by reisxd** [comment]
This happens due to the YT client/server thinking that the device running YT TV client is old and slow. The User-Agent needs to be spoofed.

**Comment by Deadinsidee3** [comment]
> This happens due to the YT client/server thinking that the device running YT TV client is old and slow. The User-Agent needs to be spoofed.

How can I do that?

**Comment by cremor** [comment]
You'd have to compile the app yourself and change this line:
https://github.com/webosbrew/youtube-webos/blob/cacdf6cfaf2d2fe2f4c708cf6891586169701ce6/assets/appinfo.json#L17

But how old is your TV, which model is it?

**Comment by Deadinsidee3** [comment]
> You'd have to compile the app yourself and change this line:
> 
> https://github.com/webosbrew/youtube-webos/blob/cacdf6cfaf2d2fe2f4c708cf6891586169701ce6/assets/appinfo.json#L17
> 
> But how old is your TV, which model is it?

Thanks for replying, my TV is

LG 65UM7100PSA. 
webOS 4.5 
05.40.45.

What user agent would you recommend me?

**Comment by byertsy** [comment]
Same issue here with my new OLED77C45LA.

**Comment by eminent-one** [comment]
Same here with C9 OLED65C9PUA

Could someone please help with the process to compile?

**Comment by byertsy** [comment]
If there is a fix for this bug (even if it means compiling it ourselves), then a step-by-step guide would be welcome.

**Comment by AyanokojiK1yotaka** [comment]
Same here on LG C9 55-inch TV / OLED55C9PUA

**Comment by bao3** [comment]
Same issue , LG  C4 , OLED77C4PCA.ACNQLJD
Firmware version: 03.11.20
webOS version: 9.1.0

**Comment by pushkaryadav** [comment]
Same issue here, LG C2. 
Software version: 13.30.85; Webos TV Version: 8.3.0-29 (number1-nameri)

**Comment by Inazuka** [comment]
@throwaway96 Do you think it's possible to provide info on how to spoof the user agent in the readme?

**Comment by Jan664** [comment]
This is a terrible problem! Think how those small pictures look on the big screen. Lord god help 🙏🙏🙏

**Comment by fejich** [comment]
Same issue , LG C4

**Comment by SrLPZ** [comment]
The issue is also with LG C2

**Comment by XtAbI** [comment]
same on LG G2

**Comment by FR33M0N7** [comment]
I've tried rebuilding with plenty of useragents (LG WebOS: https://webostv.developer.lge.com/develop/specifications/web-api-and-web-engine) with no luck. Also, with the local build, the green button functionality was lost.

Anybody? On a 4K OLED TV, this is painful. Cheers!

**Comment by vankasteelj** [comment]
Same issue here with B9 model and 0.3.5-rc1 (but still better than having ads)

**Comment by TimBass85** [comment]
Low quality thumbnails 2025, I have this problem with the latest version 0.3.7.
Any fix, please?

**Comment by FR33M0N7** [comment]
Open the options (I think it's a red or green button) and switch it on.
