### ISSUE TITLE
Question: 4_0.3.4.1 vs 4_1.174 vs 5_2.0.4

### ISSUE THREAD

**Issue by SyCoREAPER** [webosbrew/youtube-webos#197]
Just curious what the difference is between these. Oddly the two newer versions have older date stamps.

**Comment by throwaway96** [comment]
No idea what you're talking about; sorry.

**Comment by SyCoREAPER** [comment]
Thanks for taking the time to clarify and just closing instead /sarcasm 👍

**Comment by throwaway96** [comment]
Thanks for just asking an intelligible question in the first place /sarcasm 👍
