### ISSUE TITLE
Bug: SponsorBlock stops working until system reboot

### ISSUE THREAD

**Issue by Nave8** [webosbrew/youtube-webos#198]
- YTAF version: v0.3.4
used [dejavuln-autoroot](https://github.com/throwaway96/dejavuln-autoroot) to root and install latest version of YTAF through SSH.

## TV information

- webOS version:  4.4.2-11
- Firmware version: 05.50.15
- OTAID: HE_DTV_W18A_AFADABAA
- SoC:  lm18a
- Model: 65UK7500PVA

## Issue description
The problem is that sometimes SponsorBlock stops working, and I need to reboot the system in the Homebrew Channel to make it work again. This usually happens after the app has been in use for a few hours. I tried disabling and re-enabling the features with the green button, but it didn't help. Only performing a reboot through the Homebrew Channel temporarily resolves the issue until it breaks again.

**Comment by throwaway96** [comment]
That's strange. I would expect most problems to be resolved by opening a different application then going back to YTAF. I guess something could be going wrong with WAM, though. You could try killing it with `killall WebAppMgr`.

It would be very helpful if you could come up with a way to reliably trigger this issue that doesn't take hours.

Thank you for providing/correcting the TV information (although the model is obviously not OLED65G2PUA, it doesn't really matter).

**Comment by Nave8** [comment]
> That's strange. I would expect most problems to be resolved by opening a different application then going back to YTAF. I guess something could be going wrong with WAM, though. You could try killing it with `killall WebAppMgr`.
> 
> It would be very helpful if you could come up with a way to reliably trigger this issue that doesn't take hours.
> 
> Thank you for providing/correcting the TV information (although the model is obviously not OLED65G2PUA, it doesn't really matter).

Thank you for your quick reply!

![image](https://github.com/user-attachments/assets/6f006198-8922-45fa-b92c-6bcf08e4c346)
I tried my best to follow the instructions. The only 'product_id' I could find is this one.
By the way, It just happened again, and rebooting with Homebrew doesn't help anymore. I tried killing it with 'killall WebAppMgr' as you suggested, but that didn't work either. I guess I'll reinstall YTAF. Could it be because I'm using the app as a guest and not logged into a YouTube account?

**Comment by throwaway96** [comment]
I doubt the guest thing would affect SponsorBlock. The problem could be on the SponsorBlock server side though.

`product_id` is the model (65UK7500PVA).

**Comment by Nave8** [comment]
> I doubt the guest thing would affect SponsorBlock. The problem could be on the SponsorBlock server side though.
> 
> `product_id` is the model (65UK7500PVA).

My bad, I thought I had changed it 😅. I reinstalled YTAF, but the problem persists—SponsorBlock still doesn't work. Maybe it is server-side. Does it work for you at the moment?

**Comment by cremor** [comment]
SponsorBlock seems to have a problem server side right now. Some videos just don't load any sponsor segments. But some do. I even just watched a video on YTAF on my LG tv which had sponsor segments, but now the same video doesn't have any - even on the desktop browser.

**Comment by Nave8** [comment]
@cremor @throwaway96
Thank you both for your time. Upon checking, some services are down, it is probably the reason. I'll keep investigating why this is happening, as it's occurring more frequently, so I'm not sure if I'm always watching videos during downtime.
https://status.sponsor.ajay.app/
