### ISSUE TITLE
Sponsorblock broken

### ISSUE THREAD

**Issue by cbynep** [webosbrew/youtube-webos#2]
Hi, Sponsorblock integration no longer works since 0.1.1 update running on webos 5.2.1.
It's enabled in app settings, but it's not skipping promotions, nor displaying colored segments in videos.

**Comment by Miladiir** [comment]
+1 I have YT Premium or whatever it is called now. I tried uninstalling and reinstalling, logging out and back in.

**Comment by cbynep** [comment]
Upd. sponsorblock functionality is back for now at least, so must have been on their/api side, since there was no update to this app.

**Comment by Miladiir** [comment]
For me also. Sorry for bothering you.

**Comment by Informatic** [comment]
Hey! Sorry for missing these issues. Somehow github doesn't automatically start watching when repositories forked off in organizations...

As of 0.1.1 we are using a non-public proxy to fix issue of broken Let's Encrypt CA on webOS devices. A ~week ago upstream SponsorBlock API moved over to Cloudflare, which technically fixed certificates issue, but broke our proxy, which I totally missed, up until 3 days ago...

We should probably roll back to official API endpoint now that this is fixed upstream.

**Comment by ajayyy** [comment]
Cloudflare cert is a temporary sitation, so I suggest sticking with the proxy for now. I'll let you know if I get zeroSSL working.

**Comment by Informatic** [comment]
Closing since this has already been fixed. Please ping me again in case this fails... :)

**Comment by Informatic** [comment]
@ajayyy Hey, seems like CloudFlare is currently blocking off requests from our proxy since around 2022/02/06 19:00 UTC. (403 - https://sponsorblock.inf.re/api/skipSegments/aaaaa)
Is there some whitelist you could put our proxy on? (all requests are coming from `188.165.2.102/32`) Shall we add some extra source IP headers maybe?

**Comment by ajayyy** [comment]
Added that IP to the whitelist and disabled cloudflare proxying for now

**Comment by ajayyy** [comment]
I got zero ssl working, and it will be used when cloudflare is disabled (See https://wiki.sponsor.ajay.app currently running without cloudflare). So, you can probably remove the proxy now.
