### ISSUE TITLE
Bug: Everytime I open the video bar while watching, the screen goes black

### ISSUE THREAD

**Issue by zapathos** [webosbrew/youtube-webos#205]
## YTAF information

- YTAF version: 0.3.4

## 0.3.4

- webOS version: 4.4.0
- Firmware version: 05.50.40
- OTAID: HE_DTV_W18R_AFAAATAA
- SoC: m3
- Model: 43LK571C-SB

## Issue description

 I don't know when exactly this started, but for a few days now (probably a week ago) everytime I watch a video and go to like it, or add subtitles (that menu bar when you press OK button or the arrows) the screen goes black, but the audio goes on, and this disappears when I exit the menu. IDK if it's a bug and IDK how to uptade the youtube adfree, so anything helps.

**Comment by throwaway96** [comment]
See #203.
