### ISSUE TITLE
Bug: Video goes black while playback controls overlay is visible

### ISSUE THREAD

**Issue by shoffing** [webosbrew/youtube-webos#207]
## YTAF information

- YTAF version: 0.3.4

## TV information

  - webOS version: 9.2.0
  - Firmware version: 23.20.50
  - Device: OLED77C3PUA
  - OTA ID: HE_DTV_W23O_AFABATAA
  - SoC: o22n

## Issue description

- Play any video.
- Press remote button to open video controls overlay.
- Controls become visible on screen, **video goes black** in the background.
- Closing controls, video is visible again.
- Of note: Side-bar overlays (description, channel info, comments, playback settings) *do not* cause the video to go black. Only the "full screen" overlay of the video controls, and scrolling down from that into related videos.

**Comment by eadyo** [comment]
Can confirm, just noticed it too.

**Comment by Avelayy** [comment]
its fixed in newest release: https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.5-rc1

**Comment by realPrix** [comment]
This happens again since the new ui change, Im on webos 25 / 10.2.0-42

**Comment by greenythebeast** [comment]
@fire332 Can confirm this is happening again
