### ISSUE TITLE
Bug: video disappears when scrubbing

### ISSUE THREAD

**Issue by byertsy** [webosbrew/youtube-webos#209]
- YTAF version: 0.3.4

## TV information

- webOS version: 9.2.0-1801
- Model: OLED77C45LA

## Issue description

When playing a video the video will disappear when I access the player menu, leaving a black screen.

**Comment by shaggybyte** [comment]
I have the same issue for a week.

**Comment by cremor** [comment]
Duplicate of #203
Already fixed in v0.3.5-rc1
