### ISSUE TITLE
Not showing Shorts preview/thumbnail.

### ISSUE THREAD

**Issue by Garm19** [webosbrew/youtube-webos#211]
It's been a while now but when browsing on the home screen, I can only see the title of the Short, not the preview. See pic attached.
![Uploading WhatsApp Image 2024-10-22 at 08.55.13_b55a2d64.jpg…]()

**Comment by Garm19** [comment]
![WhatsApp Image 2024-10-22 at 08 55 13_b55a2d64](https://github.com/user-attachments/assets/cec8c9fc-7df8-4d6b-a8ef-630ad353f72a)

**Comment by kaiserskim** [comment]
Same issue here.

**Comment by fire332** [comment]
Closing in favor of #210

**Comment by drylmrls** [comment]
Issue looks to have re-appeared on me for v0.3.6

YTAF v0.3.6 (rooted)
webOS version: WebOS24 / 9.2.1-2605
Firmware version: 23.20.56
Model: OLED42C2PSA

![Image](https://github.com/user-attachments/assets/d63ca82d-9279-47ac-9a4d-93439eb0abfc)
