### ISSUE TITLE
Bug: Can't disable Auto-play next video

### ISSUE THREAD

**Issue by ANewDawn** [webosbrew/youtube-webos#212]
## YTAF information

- YTAF version: v0.3.5-rc1

## TV information

- webOS version: 8.2.0-20
- Firmware version: 03.20.55
- OTAID:
- SoC:
- Model: UR78006LK

## Issue description

In settings when trying to turn off auto play next video, a pop up displays something went wrong.

Have uninstalled and reinstalled app same issue.

![2024-10-23-12-35-52-106~2](https://github.com/user-attachments/assets/5bb76084-610a-4881-887a-118594329063)

**Comment by fire332** [comment]
Do you still have this issue?

**Comment by ANewDawn** [comment]
No seems to have fixed itself now
