### ISSUE TITLE
UI Question

### ISSUE THREAD

**Issue by ESLproject** [webosbrew/youtube-webos#214]
I was reading the github desc and i saw this image https://raw.githubusercontent.com/webosbrew/youtube-webos/refs/heads/main/screenshots/2_sm.jpg which shows diff UI for the youtube-webOS app it looks way diff from main am using 28inch TV how can i make my youtube look like thia:

![image](https://github.com/user-attachments/assets/4be84330-5564-45d4-8807-ac0309067d56)

**Comment by ESLproject** [comment]
anyone has Idea?

**Comment by ESLproject** [comment]
@throwaway96

**Comment by fire332** [comment]
There's no practical way to change the YouTube UI layout this extensively. We only get what is given by YouTube.
