### ISSUE TITLE
Black screen when displaying progress bar and video options.

### ISSUE THREAD

**Issue by 1bertox** [webosbrew/youtube-webos#215]
When I'm watching a video, and I activate the progress bar and video options, the video disappears and there's a black screen with only the audio.

![image](https://github.com/user-attachments/assets/e77e3530-4c52-4b28-b8f1-df08ac778883)

DEVICE: LG OLED65C9PSA
FIRMWARE: 05.40.61
webOS: 4.10
YTAF version: v0.3.4

**Comment by dperezbr** [comment]
fixed in rc #209

**Comment by ShalokShalom** [comment]
@1bertox Can you close this?

**Comment by mongeme** [comment]
Is there a way to RC1 fix update reflect to webos Homebrew channel?

**Comment by X4V1** [comment]
Any idea why the rc is not yet released 3 weeks later? Is it coming soon? If not, any idea how to install the rc from homebrew ou webos manager ?

**Comment by 1bertox** [comment]
Resolvido.
