### ISSUE TITLE
Callback was already called.

### ISSUE THREAD

**Issue by ShalokShalom** [webosbrew/youtube-webos#222]
Hi there !

I figured, the newest release has an incorrent (old) version number [as its file name](https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.5-rc1). 
But this is probably unreleated. 

My issue is, that I cant install the newest version of YTAF on my setup, that has worked before. 

```
[⚡] × ares-install youtube.leanback.v4_0.3.4_all.ipk
(node:4228) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[Info] Set target device : E9
Installing package youtube.leanback.v4_0.3.4_all.ipk
ares-install ERR! uncaughtException Error: Callback was already called.
```

## YTAF information

- YTAF version: 0.3.5-rc

## TV information

  - webOS version: 4.10.0-17
  - Firmware version: 05.40.45
  - Model: OLED55E97LA

**Comment by ShalokShalom** [comment]
I think I may have run into some issue with ares. 

Even after setting my device as default, and ares showing its correct IP, I get this:

```
sudo ares-install youtube.leanback.v4_0.3.5_all.ipk
```
```
(node:6769) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[Info] Set target device : emulator
ares-install ERR! [syscall failure]: connect ECONNREFUSED 127.0.0.1:6622
ares-install ERR! [Tips]: Connection refused. Please check the device IP address or the port number
```

**Comment by UberTurmio** [comment]
Had the same problem and after digging, found out that the problem is in ares, not in YTAF.
The npm my ares was using npm version 21, so had to use node version manager to set the default to 16.
After that, it worked like charm.

**Comment by ShalokShalom** [comment]
Thanks a lot!
