### ISSUE TITLE
Bug: <Video playback issue: Screen turns black when pressing Enter to control playback>

### ISSUE THREAD

**Issue by omti1** [webosbrew/youtube-webos#224]
## YTAF information

- YTAF version:0.3.4

## TV information

  - webOS version: 8.4.0
  - Firmware version: 13.40.90
  - OTAID: HE_DTV_W23A_AFADATAA
  - SoC: lm21ann
  - Model: 65UR73006LA

## Issue description

Hi,

I’m experiencing an issue with video playback after installing the latest version of the application. Here are the details:
When I press the Enter button on the remote to either:

When I press the Enter button on the remote to either:

- Advance the video by pressing once, or
- Stop the video by pressing twice,

the screen goes black. To restore the video display, I have to press the Back button on the remote, which brings the video image back..

**Steps to Reproduce**

1. Start playing a video.
2. Press Enter once to advance the video or twice to stop it.
3. Notice that the screen turns black.
4. Press the Back button to make the video reappear.

**Expected Behavior**
The video should respond to the Enter button commands without the screen turning black.

Please let me know if any additional logs or debugging info are required. Thanks for the help!

**Comment by Nasyncs** [comment]
Experiencing the same issue as well; it started a couple of days ago.

**Comment by ripper-7** [comment]
Seems like this bug is fixed in YTAF version:0.3.5. I am not sure when will this release tho.

**Comment by hugodigio** [comment]
Same problem here. Waiting for an update in homebrew channel :)

**Comment by Gagac44** [comment]
Same issue on my LG OLED C9. This problem occurred after reinstalling YT Add Free.

**Comment by Rushan4eg** [comment]
This problem resolved in this release https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.5-rc1

**Comment by Gagac44** [comment]
Thanks, but where can I download it? The last release is still v0.3.4. Or will it be released soon?

**Comment by Rushan4eg** [comment]
> Thanks, but where can I download it? The last release is still v0.3.4. Or will it be released soon?

Just go to my link above, scroll down to asset and find .ipk link

**Comment by Gagac44** [comment]
Thank you. I was just confused because the latest release is stated as v0.3.4 from Oct 19. It's also installed as v0.3.4, but the bug has been fixed. There is still the bug with shorts which have no video, just sound and the low image resolution on preview images, but at least the black screen bug has been fixed.

**Comment by fire332** [comment]
I'm closing this issue since it's already resolved in v0.3.5.

@Gagac44 The shorts bug is fixed by #235 which is unmerged pending additional testing. If you have webOS 4 (not firmware version) and you would like to help push the PR through, it would be appreciated.

**Comment by Anguszzzzzzz** [comment]
I am having this issue again on 0.3.6. I'm not sure what changed as I didn't update the app recently, and it was working fine.
