### ISSUE TITLE
Bug: Error showing Insufficient storage space despite having enough space for installation

### ISSUE THREAD

**Issue by WeAreLegion999** [webosbrew/youtube-webos#225]
## YTAF information

- YTAF version: 0.3.4 & 0.3.5

using ipk file of v0.3.5-rc1 "youtube.leanback.v4_0.3.4_all.ipk" 
AND
directly Install from Available store 0.3.4

## TV information

  - webOS version: 8.3.0-29
  - Firmware version: 13.30.85
  - OTAID: HE_DTV_W22O_AFABATPU
  - SoC: o22
  - Model: OLED55C2PCC

## Issue description

Cannot install Youtube Adfree despite having sufficient storage space. 
Error message: Failed to install Youtube Adfree, Can't install because of insufficient space, More info about the error: FAILED_IPKG_INSTALL

All other apps install fine from webos dev manager, like crunchyroll etc.

![image](https://github.com/user-attachments/assets/b23a6694-1ba2-49e2-abab-c1946fe0c702)
![image](https://github.com/user-attachments/assets/01d59ae2-2b59-4873-a639-e40e1ef5837e)

Free space as shown in webos dev mgr is 2GB/3GB.
TV information menu shows 1.77GB/2.69GB available internal storage
I have restarted both webos dev manager and the tv (powered completely off from socket) but no change

Prior to this, Adfree Youtube was already installed. I uninstalled it because of the black screen issue when displaying the UI. When i tried to reinstall it, there was 0 MB left in the TV storage, so it showed the same insufficient storage error. i proceeded to delete some files of kodi (.core files) to free up space. There was about 2GB free shown after that. But the error still persists, both when trying to install 0.3.5 from file explorer and as well as 0.3.4 from available app store

**Comment by WeAreLegion999** [comment]
Tried it on a new PC with a fresh install of webos dev manager. issue persisted.

i then downloaded 0.3.3 from releases, and was able to install it fine. proceeded to update to 0.3.4 through webos dev mgr and then downloaded the new fix v0.3.5-rc1 and installed it while Adfree Youtube 0.3.4 was already installed. all black screen issues are now solved.

but the original issue remains unsolved.

**Comment by fire332** [comment]
This is not an issue with YTAF. Please file an issue at `webosbrew/dev-manager-desktop` instead, or see this related issue: webosbrew/dev-manager-desktop/issues/187
