### ISSUE TITLE
Bug: can't install youtube adfree on webos 24

### ISSUE THREAD

**Issue by Reo0o** [webosbrew/youtube-webos#227]
I just had new tv.

It's on webos 24 (9.1.0) so can't be rooted.
I enabled dev mode and linked the tv to pc using webos dev manager v1.9.5 and connected successfully.
I could install latest homebrew channel and worked.
But can't install YT adfree at all.
1. tried homebrew channel.
2. tried webos dev manager from available list 
3. tried webos dev manager to install the ipk file manually

but all of them failed 
I downloaded latest ipk "youtube.leanback.v4_0.3.4_all.ipk".

any ideas to solve this issue ?

**Comment by UberTurmio** [comment]
Any errors? 
Also did you remember to delete the normal youtube app first?

**Comment by Reo0o** [comment]
I had no errors
But i didn't delete original YouTube
When i deleted it, it was installed normally

Thanks for the tip
