### ISSUE TITLE
Low resolution thumbnails

### ISSUE THREAD

**Issue by Gartorf** [webosbrew/youtube-webos#231]
## YTAF information

- YTAF version: 0.3.4

## TV information

- webOS version: 9.2.2 - 1804
- Firmware version: 23.20.38
- OTAID:
- SoC:
- Model: LGOLED55C4AUA

## Issue description

When using YTAF, all video thumbnails are low resolution/blurry
Text and interface are fine, only picture thumbnail is affected. Once you start the video everything plays in proper resolution.
YTAF options panel has every box checked except for "Hide Youtube Logo" 

There is another report from last year covering the same bug, but it has since closed:
https://github.com/webosbrew/youtube-webos/issues/111

Thank you!

**Comment by fire332** [comment]
Closing in favor of #196.
