### ISSUE TITLE
Bug: Cannot change playback speed, the option is not available.

### ISSUE THREAD

**Issue by mahenkpatel** [webosbrew/youtube-webos#233]
## YTAF information

- YTAF version: 0.3.4

## TV information

  - webOS version: 9.2.2
  - Firmware version: 23.20.38
  - OTAID: HE_DTV_W24G_AFABATAA
  - SoC: o22n2
  - Model: OLED65C4XLA

The option to change playback speed is not available on the app. The option just says "Not available on this device"
<!--

**Comment by 0xMNT** [comment]
same for me here.
  
Message: "playback speed is not available on this device"

- webOS Version: webOs24 / 9.2.1-2604
- Model: 65C3

**Comment by fire332** [comment]
Variable playback speed cannot practically be added without switching to Cobalt, and that is not planned due to various issues.
