### ISSUE TITLE
> Thank you! Will this be in the next release or how do I install this fix onto my 0.3.4 version? (Newbie question I know!)

### ISSUE THREAD

**Issue by Kaiman8-art** [webosbrew/youtube-webos#237]
> Thank you! Will this be in the next release or how do I install this fix onto my 0.3.4 version? (Newbie question I know!)

With Node.js 22 LTS installed:
- Use `git` to clone my fork on this branch, or download it [here](https://github.com/fire332/youtube-webos/archive/refs/heads/thumbnail-quality.zip) and extract it.
- Open the folder in terminal and run these commands:
  1. `npm install`
  1. `npm run build && npm run package`
  2. Use webOS Dev Manager to install the `.ipk` file.

_Originally posted by @fire332 in https://github.com/webosbrew/youtube-webos/issues/236#issuecomment-2558308606_
            
Excuse me, could you tell me the steps to open the folder in the terminal? Is it the webOS dev manager terminal?
Thank you very much, I am a newbie in this programming thing.

**Comment by fire332** [comment]
Please ask Google or chatGPT and come back if you're stuck on something particular. I like having more people willing to test these builds but these types of questions aren't for an issue tracker.
