### ISSUE TITLE
YouTube Updates

### ISSUE THREAD

**Issue by strdik** [webosbrew/youtube-webos#27]
Hello, the HOMEGROWN YouTube CHANNEL has been updated, and the old version has remained on the webos YouTube club, please update

**Comment by strdik** [comment]
in general, YouTube disappeared in the webos club market
![Uploading IMG_20220120_214016.jpg…]()

**Comment by Ruthenic** [comment]
Bring it up with whoever runs https://webosapp.club, not us (we don't run it (i think?))
