### ISSUE TITLE
Change to official Youtube Icon

### ISSUE THREAD

**Issue by dimitrij2k** [webosbrew/youtube-webos#29]
Any chance to change to official Youtube Icon in the ribbon menu?

**Comment by NguyenASang** [comment]
@dimitrij2k You want this ?

Icon
![icon](https://user-images.githubusercontent.com/87893636/150925726-c8e03375-1999-4947-a542-e6c1f8723261.png)

Large icon
![largeIcon](https://user-images.githubusercontent.com/87893636/150925733-85b6e6ed-69d1-4eac-908e-640113c5735f.png)

@Informatic What do you think of this idea?

**Comment by DavidBuchanan314** [comment]
Hm I wonder if this would be a copyright/trademark issue.

**Comment by NguyenASang** [comment]
@DavidBuchanan314 idk, I found this logo on the internet.

**Comment by DavidBuchanan314** [comment]
That's now how copyright and trademark laws work lol

**Comment by NguyenASang** [comment]
@DavidBuchanan314 But what can they do when we take their pictures? I'm just a newbie so I don't know much about this.

**Comment by DavidBuchanan314** [comment]
They can file a DMCA takedown notice against the github repo, or the webosbrew web host, or the DNS registrar, or any other intermediate infrastructure.

**Comment by dimitrij2k** [comment]
Is there a way to change the icon without compiling?

Why i want a new Icon? Because the actual Icon looks like VLC Player ;-)

**Comment by Informatic** [comment]
If your TV is rooted you can replace any app icon/asset - these are generally images in `/media/developer/apps/usr/palm/applications/APP.ID` (or `/media/cryptofs/apps/usr/palm/applications/APP.ID` in case of Content Store apps) - where `APP.ID` is id of an application you want to poke at - eg. `youtube.leanback.v4` in case of YouTube. `appinfo.json` file there contains information about the app - which looks like this one: https://github.com/webosbrew/youtube-webos/blob/main/assets/appinfo.json#L8-L9 - `icon` and `largeIcon` are filenames of icons rendered in the UI.

You can modify these files by enabling SSH Server in Homebrew Channel settings and using something like WinSCP on Windows or `scp` on Linux/Mac. Default `root` user password is `alpine`.

**Comment by dimitrij2k** [comment]
❤️❤️❤️ Thank You!

Piotr Dobrowolski ***@***.***> schrieb am Di. 25. Jan. 2022
um 12:27:

**Comment by fire332** [comment]
Will not be changed due to legal reasons.
