### ISSUE TITLE
[Polish language only] Autostart aplikacji z marketu.

### ISSUE THREAD

**Issue by LifelessLife** [webosbrew/youtube-webos#32]
Witaj @Informatic 
Jest możliwość dodania aplikacji do źródeł/autostartu z oficjalnego sklepu? Chodzi o 'siptv' który niestety nie jest podatny na komendę z README youtube-webos homebrew.
`luna-send-pub -n 1 'luna://com.webos.service.eim/addDevice' '{"appId":"siptv","pigImage":"","mvpdIcon":""}'`
to nie działa, podejrzewam, że ma odniesienie tylko do homebrew które siedzi w innym folderze niż sklepowe aplikacje.

Aplikacja nie zawiera przedrostków com.xx.xx jest w folderze siptv po prostu:
/media/cryptofs/apps/usr/palm/applications/siptv/

Z góry dziękuję za pomoc.

**Comment by q3k** [comment]
(Seulement en Français)

Salut @LifelessLife

Il faut que tu ajoutes d'abord `"supportGIP":true` dans le fichier appinfo.json de siptv, dans ton cas ça sera dans `/media/cryptofs/apps/usr/palm/applications/siptv/application.json`. Après avoir faire ça, `luna-send-pub -n 1 ...` devrais dèsormais marcher.

D'ailleurs, ici c'est pas le meilleur endroit pour ce genre de questions. S'il-te-plait, pour la prochaine foit, pose ce type de questions sur Discord ou Matrix. De préférence en Anglais, nous ne parlons pas tous français et polonais.

**Comment by LifelessLife** [comment]
Merci beaucoup, je suis déjà en train de tester et je m'excuse.

**Comment by Informatic** [comment]
Memes aside - we have a separate repository full of homebrew app ideas, and "Autostart Manager" (which would basically do exactly what you just had to do by hand) was one of the first ones we had - https://github.com/webosbrew/apps-repo/issues/23 - just looking for someone to commit their time to work on this.
