### ISSUE TITLE
Readme instructions on how to update app

### ISSUE THREAD

**Issue by NeoNavras** [webosbrew/youtube-webos#34]
I'm missing instructions on how to update the app. I did the manual install via the official WebOS SDK. Do I need to remove the app first before I can install an updated .ipk? Or is it possible to install the new .ipk without removing the previous version first? Is app data retained when upgrading? I guess when I remove and reinstall the app data is gone.

**Comment by Informatic** [comment]
webOS supports app upgrades/downgrades properly - just install a new
version over existing installed one. (Without removing anything)

**Comment by NeoNavras** [comment]
Thanks it worked!
