### ISSUE TITLE
Returns an error in the browser

### ISSUE THREAD

**Issue by dryna2017** [webosbrew/youtube-webos#36]
Hello, on the lg webos 3.9.0 TV, when typing any page in the browser, it gives an error, is it possible to somehow update certificates, can you tell me what commands you need to type.
![IMG_20220207_163558](https://user-images.githubusercontent.com/96721916/154073810-4339fc06-c82c-490d-9767-9f4482db19ee.jpg)

**Comment by Wtcheesecakes** [comment]
Can't read or speak russian, But perhaps this is what is required? https://github.com/tf318/lg/blob/main/README.md

**Comment by dryna2017** [comment]
> Не умею читать и говорить по-русски, А может, это то, что нужно? https://github.com/tf318/lg/blob/main/README.md

Что то я не понял что вы имели ввиду

**Comment by Wtcheesecakes** [comment]
> > Не умею читать и говорить по-русски, А может, это то, что нужно? https://github.com/tf318/lg/blob/main/README.md
> 
> Что то я не понял что вы имели ввиду не умеешь читать и говорить по русски

As in I can't speak Russian (so I don't know what the picture says)

**Comment by dryna2017** [comment]
> > > Не умею читать и говорить по-русски, А может, это то, что нужно? https://github.com/tf318/lg/blob/main/README.md
> > 
> > 
> > Что то я не понял, что вы имеете ввиду не умеете читать и говорить по русски
> 
> Например, я не говорю по-русски (поэтому я не знаю, что написано на картинке)
It says there about the certificate, but the time is set up correctly and your link did not help, and this is a translation. (The server security certificate is invalid! The wrong time can lead to an error. Check the time settings and make sure the current time is correct)
