### ISSUE TITLE
Remove "YouTube End Cards"

### ISSUE THREAD

**Issue by vttai96** [webosbrew/youtube-webos#40]
If possible, please integrate this feature to eliminate the hassle of watching videos.

![image](https://user-images.githubusercontent.com/52731691/157153079-2279f0c2-5564-4c0b-99dd-39487c82f416.png)

**Comment by fire332** [comment]
Closing in favor of #126.

**Comment by xxxMentoLxxx** [comment]
Will this "function" be integrated?

**Comment by ANewDawn** [comment]
> Will this "function" be integrated?

It's implemented in YouTube fork below. Enable it in settings panel with green button on remote.

https://github.com/NicholasBly/youtube-webos/releases
