### ISSUE TITLE
As of yesterday, the app does not start, stuck at YouTube splash screen

### ISSUE THREAD

**Issue by gorshco** [webosbrew/youtube-webos#42]
Has anyone else experienced this?

**Comment by Informatic** [comment]
Seems to work for me. Are you running the latest app version?

Which webOS version are you on?

**Comment by gorshco** [comment]
Latest app version, webOS 6.2.1-2410, software version 03.25.10

**Comment by Informatic** [comment]
Seems to work well on my webOS 3.8 TV. Can you please try removing the YouTube app (long press "OK" button on app icon, and you'll probably get some "X" button that'll remove the app) and installing it again? This will clear app data/cache, which may have gotten corrupted for some reason.

**Comment by gorshco** [comment]
That did the trick, I've probably should have started with that...
