### ISSUE TITLE
Side menu (icons) disappeared

### ISSUE THREAD

**Issue by igorkulman** [webosbrew/youtube-webos#44]
For the last few days I noticed all the icons gone and replaced by strange symbols and today the menu completely disappeared making the app quite unusable.

I tried uninstalling the app and installing it again (0.3.1 from the homebrew "store") but it did not help.

![5D6B3FFE-7E20-43C2-B410-33290CF34215](https://user-images.githubusercontent.com/4746070/163039277-1ac5ce36-338f-4ac7-852e-2747f2e34c78.jpeg)

**Comment by igorkulman** [comment]
Today I am back to broken icons but at least the menu is back and usable

![D845A210-495D-465A-994F-C03B5AEF6B04](https://user-images.githubusercontent.com/4746070/163114550-0be23cb1-ce02-46db-bbf6-9f81436f9536.jpeg)

**Comment by luckygreen** [comment]
@igorkulman Yup, I am seeing the identical messed up icons on my LG TV. Never had the menu disappear entirely, though. Just the wrong icons.

**Comment by patrickwinslow** [comment]
Confirmed with model UH6150.

**Comment by Sorinaki** [comment]
Same issue here, but I uninstalled this version and re-installed the "original" YT app - it has the same weird icons, so it might be something screwed by the LG themselves.

**Comment by igorkulman** [comment]
Icons are back for some reason, closing.
