### ISSUE TITLE
Question about uninstalling the official app before installation

### ISSUE THREAD

**Issue by ammgws** [webosbrew/youtube-webos#45]
Could you please tell me what happens if the official YouTube app is not uninstalled before installation?
(From the README: "Official YouTube app needs to be uninstalled before installation")

Asking because I was wondering if the Youtube Kids app needs to be uninstalled as well.

**Comment by joaopedrosgs** [comment]
it simply fails to install

**Comment by ammgws** [comment]
OK if that is all then I can just try it and see.

Thanks
