### ISSUE TITLE
Error in webos app. club

### ISSUE THREAD

**Issue by dryna2017** [webosbrew/youtube-webos#46]
Hello, tell me what happened to the webos app. club, it turns for a long time and gives an error
![IMG_20220422_173308](https://user-images.githubusercontent.com/96721916/164746322-fb66b12d-df69-40c8-b70d-78fb8f3cfd30.jpg)
![IMG_20220422_173308](https://user-images.githubusercontent.com/96721916/164746484-f1080a8c-14e6-4200-8237-faf615f26a2e.jpg)

**Comment by tuxuser** [comment]
webosbrew is in no way affiliated with webosapp.club!
