### ISSUE TITLE
Add auto-4k

### ISSUE THREAD

**Issue by ghost** [webosbrew/youtube-webos#48]
Hi, it would be good to add a feature force the highest quality resolution. Thanks

**Comment by MasterV25** [comment]
Agreed. It is extremely annoying to see a video autoplay at 720p when it is available in 2160p and plays at 2160p when manually selected without issues.

**Comment by throwaway96** [comment]
Is there a way to change the resolution with a keypress or some semi-official API?

Reaching into the YouTube JS is not feasible. It's (at least) minified. Even if you managed to find a way to change the resolution with internal methods, the identifiers may all change the next time Google rebuilds the site.
