### ISSUE TITLE
[IDEA] Adding comment section view/adding comments

### ISSUE THREAD

**Issue by konrad-bak** [webosbrew/youtube-webos#49]
First of all: Thank you for this app!

Adblock and sponsorblock is what makes YT on tv usable at all for me, you're truly legends.

What would make the app even more superior from official app: is adding comment section.

**Comment by amberdambey** [comment]
Fantastic suggestion, however, adding an entire comment section is pretty hard to do. I don't think the YouTube API (for TVs, anyway) allows for accessing or posting comments. Although, it would be a nice and useful feature, I agree. It just would be hard to implement.

Hopefully the devs work on a way to view comments. I currently need to switch back and forth between my phone and the TV to watch the video and read its comments.

**Comment by konrad-bak** [comment]
I'm a ReactJS dev, but apps for TVs like this is completely new territory for me - so feel free to educate me.

I'm thinking - if YouTube API is againstus, maybe create a workaround solution, and simply add a popup view (like the options for SponsorBlock on green button), where we simply open same video page in desktop mode, and simply scrape the whole comment section, displaying only that)

not the prettiest solution, but also the option won't be used that often, so the 1-2sec lag won't be a problem)

What do you think?
