### ISSUE TITLE
[IDEA] Bring up the video description as one of the buttons on overlay

### ISSUE THREAD

**Issue by konrad-bak** [webosbrew/youtube-webos#50]
Until recently, I was sure the yt app just doesn't show video descriptions at all - until I found out it's at the very bottom of "paused video overlay", down under all sponsored and recommended videos - and I'm sure I am not alone.

It would be very useful to add "Open video description" as one of the buttons, maybe after the like&dislike buttons?

**Comment by fire332** [comment]
The description can be found by selecting the video title in the player controls overlay.
