### ISSUE TITLE
SponsorBlock not working

### ISSUE THREAD

**Issue by Cpt-Night** [webosbrew/youtube-webos#51]
First off this app is awesome!!!
But just started having an issue.
SponsorBlock is not working.
AdBlocking is working fine.

Doesn't skip any Sponsor segments at all during videos.
Tried on 2 TV's.
One Rooted and one using Developer Mode.
Have tried SponsorBlock on my computer and it works just as expected on the same video.

**Comment by Informatic** [comment]
Thanks for reporting in. This should be back up in a minute.

We are still going through a custom proxy to SponsorBlock API.

![image](https://user-images.githubusercontent.com/1131102/176714542-b79388e4-c41a-490a-b146-1826e32f308b.png)

Today at around 6:40AM CET they stopped serving the API on their existing `api.sponsor.ajay.app` domain. I already had alerting rules set up for that, which... did not have any alert targets. I should be able to respond quicker next time.

**Comment by Cpt-Night** [comment]
No problem.

it seems to be working again.
Thanks!

**Comment by tomikaka22** [comment]
Sadly it still doesn't work for me. The TV makes requests to "sponsorblock.inf.re" to no avail.
