### ISSUE TITLE
[IDEA] Add YouTube 2X speed

### ISSUE THREAD

**Issue by UltraHDR** [webosbrew/youtube-webos#52]
This is available on the Xbox/PS5 YouTube app

**Comment by Visiraptor** [comment]
I had the same suggestion, but the developers might not answer. 
I would be nice to have the option to set the speed manually like on the website. "X2" might be too fast for me personally but "1.25" is good or maybe "1.5". The official website of course has even more options.
Hope this could be added soon. 
Thank you for your work.
