### ISSUE TITLE
Related videos/channels/topics

### ISSUE THREAD

**Issue by fergardi** [webosbrew/youtube-webos#54]
Hello!

First of all, I want to thank you and your team for your spectacular work. State of the art YouTube has become unwatchable due to adds, and this app is a huge quality of life improvement.

But I was wondering if there is an issue with video history, video recommendations, or maybe the video suggestion algorithm. With the original YouTube app, after days of exploring and watching some videos/channels, it would start suggesting related topics, (mainly new or recently uploaded) videos, and channels, even without being logged in with my google account.

I cannot see the same behavior in this app, at least by not logging in. After watching some videos, and closing and reopening the app, it flushes all watched video history (except the text search history), so I need to search again for channels or new videos of the same topics. Is there any configuration related to this? Is the logging into google account needed for this feature? Or maybe it is disabled due to the trackers blocking features?

Thanks in advance.

**Comment by jospezial** [comment]
Recommendations work here. Not logged in. No yt/google account.
Do you close the app with back key or exit key?

**Comment by fergardi** [comment]
I usually switch the app to another one by using the home key, or directly turn off the tv, so I don't believe this is the problem.

For example, since my first installation, all my search history is still intact and never got wiped, so this is being stored with no issues and working fine.

However, my recommendations are not based on my usual viewed content pattern, at all. It looks random, just as a recently installed app, with no profile yet. For instance, now I'm looking at my recommendation list, and it shows videos about:

- Monster trucks
- Religious music
- Physiotherapy
- Children cartoons
- Football

None of these topics are of my interest nor I have ever watched videos about them.

That makes me wonder if this is a bug, I'm missing some configuration elsewhere, or the built-in sponsor adblocker is preventing the app for gathering information about my interests.

Thank you for your time.

**Comment by fire332** [comment]
I can't reproduce this. Videos I watch show up on my other devices' watch histories. Please re-open the issue if you're still experiencing this.
