### ISSUE TITLE
Project Dead? 

### ISSUE THREAD

**Issue by SyCoREAPER** [webosbrew/youtube-webos#69]
I love this app and am not complaining. Just wondering if this has been abandoned as it hasn't been updated in close to a year.

**Comment by Informatic** [comment]
Partially, but not really? It's just mostly feature complete. Most
bugs/issues are related to inherent platform limitations, or bugs
introduced by Google/YouTube itself, that get resolved after a while. Only
major actionable issue is blocking of "top-left" ad video on homepage - I
have started working on this in one of the pending PRs and will probably
cut a new release before end of the year.

**Comment by SyCoREAPER** [comment]
Thanks for the quick response. Like I said, please don't mistake that for question for a lack of appreciation or respect of your personal time.

I only ask because eventually older builds tend to lose functionality if not updated (like access to paid content for example, at least on Android, sure WebOS is similar to an extent).

Either way thanks again for the response and your work is appreciated and respected.
