### ISSUE TITLE
Bump version number

### ISSUE THREAD

**Issue by kapodamy** [webosbrew/youtube-webos#70]
my tv keeps reinstalling the original app

**Comment by jospezial** [comment]
@Informatic @throwaway96 
Thank you for tagging v0.3.2-rc1.
Please bump the version in .json files.

https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.2-rc1
youtube.leanback.v4_0.3.1_all.ipk
https://github.com/webosbrew/youtube-webos/releases/download/v0.3.2-rc1/youtube.leanback.v4_0.3.1_all.ipk

**Comment by throwaway96** [comment]
@jospezial 

Have you tested it? I guess I can do an 0.3.2 release, but first I'd like to hear from a few people who have run it on different webOS versions and made sure nothing major broke.
