### ISSUE TITLE
delete the account login notification

### ISSUE THREAD

**Issue by hawk573** [webosbrew/youtube-webos#75]
Hi, big kudos to LG WebOS YouTubeAdFree app working! However, I have a long-term problem with repeated annoying notifications that require account login in this application. It always appears in sequence after playing a few videos. At the end of the video, playback will stop and a notification will appear on the right side of the screen. So autoplay doesn't work and I have to unclick it every time. The solution would be to log in, but I don't want to log in. Is it possible to fix it? If so, thank you in advance! 
![IMG_20230326](https://user-images.githubusercontent.com/128277269/227795452-dba013d9-0868-485c-8ae3-3b5bb0b8c6e6.jpg)

**Comment by fergardi** [comment]
I am interested in this as well. I usually wouldn't mind to log in to get this popup to go away, but I am concerned about security if I login using a thirdparty (or hacked) youtube app. I am afraid my credentials will be captured or hijacked somehow. So I never log in. But then this popup shows up every now and then. Is there a way to disable it in the configurations?

Thanks in advance.

**Comment by fire332** [comment]
Closing in favor of #195.
