### ISSUE TITLE
Add video speed switching

### ISSUE THREAD

**Issue by teolabx** [webosbrew/youtube-webos#76]
Hello! Question - is it planned to add a function to change the speed of the video? Thank you!

**Comment by UltraHDR** [comment]
Not possible. See https://github.com/webosbrew/youtube-webos/issues/52

**Comment by tekwarfare** [comment]
@teolabx
https://github.com/GuillaumeSmaha/youtube-webos-cobalt
has working speed management, but you need to compile it yourself

**Comment by UltraHDR** [comment]
> @teolabx https://github.com/GuillaumeSmaha/youtube-webos-cobalt has working speed management, but you need to compile it yourself

Thanks! I find the UI smoother too!

**Comment by throwaway96** [comment]
Not going to happen. See #6 for more information.
