### ISSUE TITLE
TV entering screensaver mode

### ISSUE THREAD

**Issue by Alan-Gomes** [webosbrew/youtube-webos#79]
Hello, I'm on version 0.3.1 and some videos (like LTT) makes the TV enter screensaver mode

This is an example video:
https://youtu.be/c-J229FzKXk

It does not happen necessarily before/after an sponsor segment, it triggers after some time at any part of the video.

Maybe related to issue #12, but I'm in the latest version.

**Comment by AppleManDos** [comment]
I am using version web_20240304_10_RC00 and this happens to me also but only on some videos.

**Comment by azerpas** [comment]
I found it happening only on videos with black bars

**Comment by fire332** [comment]
This has been fixed for a quite few versions now. Please try the latest rc2 version and file a new issue if you're still experiencing this.

**Comment by pledi** [comment]
I'm still encountering this issue when watching LTT videos for example. 
After a certain amount of time, the screensaver turns on, I need to press a button or move the cursor for it to stop

YT: 0.37 
WebOS TV Version: 6.0.1-454907
TV Model: OLED55C16LA

**Comment by fire332** [comment]
@pledi please link specific videos where this occurs.

**Comment by pledi** [comment]
@fire332 sure thing: 
https://www.youtube.com/watch?v=A0sLQvuLwxQ
https://www.youtube.com/watch?v=Y6FDX9Qy5lg

It seems to be related to the aspect ratio, once it doesnt fit to the tv (I assume 16:9) it will sooner or later turn on the clock screensaver, while the video is playing.

**Comment by fire332** [comment]
I cannot reproduce the screensaver bug with those 2 videos. However, I do notice that the videos are stretched to fill the screen. 

Have you tried restarting your TV? And I don't mean just pushing the power button. I mean either using the restart option hidden in the settings menu, or unplugging it for a few seconds and plugging it back after turning it "off" with the power button.

**Comment by pledi** [comment]
I've updated WebOS and rooted it again, now it works again. Nonetheless thanks for the help :)
