### ISSUE TITLE
Speed adjustment request

### ISSUE THREAD

**Issue by Ninjasnaz** [webosbrew/youtube-webos#89]
Hi All,
Although I know of Issue #6, the latest WebOS official Yotube app does support selecting speed of playback. Does this mean you can work on getting the speed selector in place now?
TV: OLED55B2PUA
Software version: 03.30.74

**Comment by 0x09AF** [comment]
This is the feature the app has been lacking for years.
I support this request

**Comment by UltraHDR** [comment]
https://github.com/webosbrew/youtube-webos/issues/76#issuecomment-1670146452

**Comment by throwaway96** [comment]
Not going to happen. See #6 for more information.
