### ISSUE TITLE
Loading/Buffering

### ISSUE THREAD

**Issue by nausherwannasir** [webosbrew/youtube-webos#91]
After the recent update to my 65UQ7590PUB the app lags a lot. It has been doing this for 3,4 days now. Even though I have a fast connection, the videos are almost unwatchable. Anyone else has this issue? Any fixes?

**Comment by ajisetiawan716** [comment]
Try just reinstalled it, its work for this time.

**Comment by throwaway96** [comment]
Without more information, there's not much we can do about this. Unless there's some kind of bug in our scripts seriously hurting performance, it's probably either a network issue or just poor performance of the WAM YouTube client. After all, I assume there's a reason Google switched to Cobalt...
