### ISSUE TITLE
Cast button

### ISSUE THREAD

**Issue by rbaggio108** [webosbrew/youtube-webos#98]
How about cast button on phones? Do you have it after installing youtube ads free? In my case it disappeared :(

**Comment by U-StaSS** [comment]
I can cast from my OnePlus 8 (Android 12).
I just synced it manually first by code. After that I don't need to do it again.

**Comment by ElPumpo** [comment]
Yes casting works like the original app. It's great! Requires no setup at all it's untouched.

**Comment by dzid26** [comment]
Can you guys wake up the TV/projector from the standby?

**Comment by fire332** [comment]
It's working right now. Waking up from standby is out of scope.
